//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barista.SharePoint.SPBaristaSearchService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://barista/services/v1/")]
    [System.SerializableAttribute()]
    public partial class Document : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Barista.SharePoint.SPBaristaSearchService.FieldBase> FieldsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Barista.SharePoint.SPBaristaSearchService.FieldBase> Fields {
            get {
                return this.FieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldsField, value) != true)) {
                    this.FieldsField = value;
                    this.RaisePropertyChanged("Fields");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldBase", Namespace="http://barista/services/v1/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Barista.SharePoint.SPBaristaSearchService.FieldBaseOfdouble))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Barista.SharePoint.SPBaristaSearchService.NumericField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Barista.SharePoint.SPBaristaSearchService.FieldBaseOfstring))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Barista.SharePoint.SPBaristaSearchService.StringField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Barista.SharePoint.SPBaristaSearchService.FieldBaseOfdateTime))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Barista.SharePoint.SPBaristaSearchService.DateField))]
    public partial class FieldBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<float> BoostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Barista.SharePoint.SPBaristaSearchService.FieldIndexType IndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Barista.SharePoint.SPBaristaSearchService.FieldStorageType StoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Barista.SharePoint.SPBaristaSearchService.FieldTermVectorType TermVectorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> Boost {
            get {
                return this.BoostField;
            }
            set {
                if ((this.BoostField.Equals(value) != true)) {
                    this.BoostField = value;
                    this.RaisePropertyChanged("Boost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Barista.SharePoint.SPBaristaSearchService.FieldIndexType Index {
            get {
                return this.IndexField;
            }
            set {
                if ((this.IndexField.Equals(value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Barista.SharePoint.SPBaristaSearchService.FieldStorageType Store {
            get {
                return this.StoreField;
            }
            set {
                if ((this.StoreField.Equals(value) != true)) {
                    this.StoreField = value;
                    this.RaisePropertyChanged("Store");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Barista.SharePoint.SPBaristaSearchService.FieldTermVectorType TermVector {
            get {
                return this.TermVectorField;
            }
            set {
                if ((this.TermVectorField.Equals(value) != true)) {
                    this.TermVectorField = value;
                    this.RaisePropertyChanged("TermVector");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldBaseOfdouble", Namespace="http://barista/services/v1/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Barista.SharePoint.SPBaristaSearchService.NumericField))]
    public partial class FieldBaseOfdouble : Barista.SharePoint.SPBaristaSearchService.FieldBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NumericField", Namespace="http://barista/services/v1/")]
    [System.SerializableAttribute()]
    public partial class NumericField : Barista.SharePoint.SPBaristaSearchService.FieldBaseOfdouble {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrecisionStepField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrecisionStep {
            get {
                return this.PrecisionStepField;
            }
            set {
                if ((this.PrecisionStepField.Equals(value) != true)) {
                    this.PrecisionStepField = value;
                    this.RaisePropertyChanged("PrecisionStep");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldBaseOfstring", Namespace="http://barista/services/v1/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Barista.SharePoint.SPBaristaSearchService.StringField))]
    public partial class FieldBaseOfstring : Barista.SharePoint.SPBaristaSearchService.FieldBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StringField", Namespace="http://barista/services/v1/")]
    [System.SerializableAttribute()]
    public partial class StringField : Barista.SharePoint.SPBaristaSearchService.FieldBaseOfstring {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldBaseOfdateTime", Namespace="http://barista/services/v1/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Barista.SharePoint.SPBaristaSearchService.DateField))]
    public partial class FieldBaseOfdateTime : Barista.SharePoint.SPBaristaSearchService.FieldBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DateField", Namespace="http://barista/services/v1/")]
    [System.SerializableAttribute()]
    public partial class DateField : Barista.SharePoint.SPBaristaSearchService.FieldBaseOfdateTime {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldIndexType", Namespace="http://barista/services/v1/")]
    public enum FieldIndexType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotIndexed = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Analyzed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AnalyzedNoNorms = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotAnalyzed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotAnalyzedNoNorms = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldStorageType", Namespace="http://barista/services/v1/")]
    public enum FieldStorageType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Stored = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotStored = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldTermVectorType", Namespace="http://barista/services/v1/")]
    public enum FieldTermVectorType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yes = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WithPositions = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WithOffsets = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WithPositionsOffsets = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JsonDocument", Namespace="http://barista/services/v1/")]
    [System.SerializableAttribute()]
    public partial class JsonDocument : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataAsJsonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetadataAsJsonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataAsJson {
            get {
                return this.DataAsJsonField;
            }
            set {
                if ((object.ReferenceEquals(this.DataAsJsonField, value) != true)) {
                    this.DataAsJsonField = value;
                    this.RaisePropertyChanged("DataAsJson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentId {
            get {
                return this.DocumentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentIdField, value) != true)) {
                    this.DocumentIdField = value;
                    this.RaisePropertyChanged("DocumentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetadataAsJson {
            get {
                return this.MetadataAsJsonField;
            }
            set {
                if ((object.ReferenceEquals(this.MetadataAsJsonField, value) != true)) {
                    this.MetadataAsJsonField = value;
                    this.RaisePropertyChanged("MetadataAsJson");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchResult", Namespace="http://barista/services/v1/")]
    [System.SerializableAttribute()]
    public partial class SearchResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Barista.SharePoint.SPBaristaSearchService.JsonDocument DocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Barista.SharePoint.SPBaristaSearchService.JsonDocument Document {
            get {
                return this.DocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentField, value) != true)) {
                    this.DocumentField = value;
                    this.RaisePropertyChanged("Document");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://barista/services/v1/", ConfigurationName="SPBaristaSearchService.IBaristaSearch")]
    public interface IBaristaSearch {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://barista/services/v1/IBaristaSearch/IndexDocument", ReplyAction="http://barista/services/v1/IBaristaSearch/IndexDocumentResponse")]
        void IndexDocument(string indexName, string documentId, Barista.SharePoint.SPBaristaSearchService.Document document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://barista/services/v1/IBaristaSearch/IndexJsonDocument", ReplyAction="http://barista/services/v1/IBaristaSearch/IndexJsonDocumentResponse")]
        void IndexJsonDocument(string indexName, Barista.SharePoint.SPBaristaSearchService.JsonDocument document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://barista/services/v1/IBaristaSearch/IndexJsonDocuments", ReplyAction="http://barista/services/v1/IBaristaSearch/IndexJsonDocumentsResponse")]
        void IndexJsonDocuments(string indexName, System.Collections.Generic.List<Barista.SharePoint.SPBaristaSearchService.JsonDocument> documents);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://barista/services/v1/IBaristaSearch/DeleteDocuments", ReplyAction="http://barista/services/v1/IBaristaSearch/DeleteDocumentsResponse")]
        void DeleteDocuments(string indexName, System.Collections.Generic.List<string> documentIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://barista/services/v1/IBaristaSearch/DeleteAllDocuments", ReplyAction="http://barista/services/v1/IBaristaSearch/DeleteAllDocumentsResponse")]
        void DeleteAllDocuments(string indexName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://barista/services/v1/IBaristaSearch/Retrieve", ReplyAction="http://barista/services/v1/IBaristaSearch/RetrieveResponse")]
        Barista.SharePoint.SPBaristaSearchService.JsonDocument Retrieve(string indexName, string documentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://barista/services/v1/IBaristaSearch/Search", ReplyAction="http://barista/services/v1/IBaristaSearch/SearchResponse")]
        System.Collections.Generic.List<Barista.SharePoint.SPBaristaSearchService.SearchResult> Search(string indexName, string defaultField, string query, int maxResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://barista/services/v1/IBaristaSearch/SearchOData", ReplyAction="http://barista/services/v1/IBaristaSearch/SearchODataResponse")]
        System.Collections.Generic.List<Barista.SharePoint.SPBaristaSearchService.SearchResult> SearchOData(string indexName, string defaultField, string queryString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBaristaSearchChannel : Barista.SharePoint.SPBaristaSearchService.IBaristaSearch, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BaristaSearchClient : System.ServiceModel.ClientBase<Barista.SharePoint.SPBaristaSearchService.IBaristaSearch>, Barista.SharePoint.SPBaristaSearchService.IBaristaSearch {
        
        public BaristaSearchClient() {
        }
        
        public BaristaSearchClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BaristaSearchClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaristaSearchClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaristaSearchClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void IndexDocument(string indexName, string documentId, Barista.SharePoint.SPBaristaSearchService.Document document) {
            base.Channel.IndexDocument(indexName, documentId, document);
        }
        
        public void IndexJsonDocument(string indexName, Barista.SharePoint.SPBaristaSearchService.JsonDocument document) {
            base.Channel.IndexJsonDocument(indexName, document);
        }
        
        public void IndexJsonDocuments(string indexName, System.Collections.Generic.List<Barista.SharePoint.SPBaristaSearchService.JsonDocument> documents) {
            base.Channel.IndexJsonDocuments(indexName, documents);
        }
        
        public void DeleteDocuments(string indexName, System.Collections.Generic.List<string> documentIds) {
            base.Channel.DeleteDocuments(indexName, documentIds);
        }
        
        public void DeleteAllDocuments(string indexName) {
            base.Channel.DeleteAllDocuments(indexName);
        }
        
        public Barista.SharePoint.SPBaristaSearchService.JsonDocument Retrieve(string indexName, string documentId) {
            return base.Channel.Retrieve(indexName, documentId);
        }
        
        public System.Collections.Generic.List<Barista.SharePoint.SPBaristaSearchService.SearchResult> Search(string indexName, string defaultField, string query, int maxResults) {
            return base.Channel.Search(indexName, defaultField, query, maxResults);
        }
        
        public System.Collections.Generic.List<Barista.SharePoint.SPBaristaSearchService.SearchResult> SearchOData(string indexName, string defaultField, string queryString) {
            return base.Channel.SearchOData(indexName, defaultField, queryString);
        }
    }
}
