//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barista.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Barista.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Author: Michael Schøler, 2008
        ///// Dual licensed as MIT and LGPL, use as you like, don&apos;t hold me responsible for success or failure though
        ///Array.prototype.compareTo = function(compareAry) {
        ///  if (this.length === compareAry.length) {
        ///    var i;
        ///    for (i = 0; i &lt; compareAry.length; i+=1) {
        ///      if (Object.isArray(this[i]) === true) {
        ///        if (this[i].compareTo(compareAry[i]) === false) {
        ///          return false;
        ///        }
        ///        continue;
        ///      }
        ///      else if (this[i] !== compareAry[i]) {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string jsonDataHandler {
            get {
                return ResourceManager.GetString("jsonDataHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(b){var a={VERSION:&quot;2.2.0&quot;,Result:{SUCCEEDED:1,NOTRANSITION:2,CANCELLED:3,ASYNC:4},Error:{INVALID_TRANSITION:100,PENDING_TRANSITION:200,INVALID_CALLBACK:300},WILDCARD:&quot;*&quot;,ASYNC:&quot;async&quot;,create:function(g,h){var j=(typeof g.initial==&quot;string&quot;)?{state:g.initial}:g.initial;var f=h||g.target||{};var l=g.events||[];var i=g.callbacks||{};var d={};var k=function(m){var p=(m.from instanceof Array)?m.from:(m.from?[m.from]:[a.WILDCARD]);d[m.name]=d[m.name]||{};for(var o=0;o&lt;p.length;o++){d[m.name][p[o]]=m.to|| [rest of string was truncated]&quot;;.
        /// </summary>
        public static string stateMachine {
            get {
                return ResourceManager.GetString("stateMachine", resourceCulture);
            }
        }
    }
}
