//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barista.SharePoint.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Barista.SharePoint.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------------------------------------------------
        ///* linq.js - LINQ for JavaScript
        ///* ver 2.2.0.2 (Jan. 21th, 2011)
        ///*
        ///* created and maintained by neuecc &lt;ils@neue.cc&gt;
        ///* licensed under Microsoft Public License(Ms-PL)
        ///* http://neue.cc/
        ///* http://linqjs.codeplex.com/
        ///*--------------------------------------------------------------------------*/
        ///
        ///Enumerable = (function ()
        ///{
        ///    var Enumerable = function (getEnumerator)
        ///    {
        ///        this.GetEnumerator = getEnumerator;
        ///    } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string linq {
            get {
                return ResourceManager.GetString("linq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * mustache.js - Logic-less {{mustache}} templates with JavaScript
        /// * http://github.com/janl/mustache.js
        /// */
        ///
        ////*global define: false*/
        ///
        ///var Mustache;
        ///
        ///(function (exports) {
        ///  if (typeof module !== &quot;undefined&quot; &amp;&amp; typeof module.exports !== &quot;undefined&quot;) {
        ///    module.exports = exports; // CommonJS
        ///  } else if (typeof define === &quot;function&quot;) {
        ///    define(exports); // AMD
        ///  } else {
        ///    Mustache = exports; // &lt;script&gt;
        ///  }
        ///}((function () {
        ///  var exports = {};
        ///
        ///  exports.name = &quot;mustache.js&quot;;
        ///  exports.version = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mustache {
            get {
                return ResourceManager.GetString("mustache", resourceCulture);
            }
        }
    }
}
